{{ if and (not .Values.controller.wildcardTLS.secret) (and .Values.controller.wildcardTLS.cert .Values.controller.wildcardTLS.key) (not (index .Values "f5-tmm").tmm.Only) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "f5ingress.wildcardTLSName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "f5ingress.labels" . | nindent 4 }}
type: Opaque
data:
  tls.crt: {{ .Values.controller.wildcardTLS.cert }}
  tls.key: {{ .Values.controller.wildcardTLS.key }}
{{- end }}
