apiVersion: v1
kind: Service
metadata:
  name: ${loki_service_name}
  namespace: ${observability_namespace}
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/managed-by: bnk-forge
    app.kubernetes.io/part-of: bnk-live-observability
spec:
  type: ClusterIP
  selector:
    app: loki
  ports:
    - name: http
      port: ${loki_port}
      targetPort: http
      protocol: TCP
