apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dpdk-configurator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dpdk-configurator
subjects:
- kind: ServiceAccount
  name: dpdk-configurator
  namespace: kube-system