apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multus-ip-manager
  namespace: kube-system
  labels:
    app: multus-ip-manager
spec:
  selector:
    matchLabels:
      app: multus-ip-manager
  template:
    metadata:
      labels:
        app: multus-ip-manager
    spec:
      serviceAccountName: multus-ip-manager
      hostNetwork: true
      nodeSelector:
        node-type: high-performance
      tolerations:
      - key: high-performance
        operator: Equal
        value: "true"
        effect: NoSchedule
      - key: dpu
        operator: Equal
        value: "true"
        effect: NoSchedule
      containers:
      - name: multus-ip-manager
        image: ${ecr_registry}/multus-ip-manager:${multus_container_version}
        imagePullPolicy: IfNotPresent
        args: ["/bin/sh", "-c", "/app/script.sh daemonset"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: AWS_DEFAULT_REGION
          value: ${region}
        - name: SUBNET_ID_INTERNAL
          value: ${subnet_internal}
        - name: SUBNET_ID_EXTERNAL
          value: ${subnet_external}
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-proc
          mountPath: /host/proc
          readOnly: true
        - name: host-net
          mountPath: /host/sys/class/net
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: host-proc
        hostPath:
          path: /proc
      - name: host-net
        hostPath:
          path: /sys/class/net