apiVersion: v1
kind: ServiceAccount
metadata:
  name: bedrock-smartllm
  namespace: ${namespace}
  labels:
    app.kubernetes.io/part-of: bedrock-smartllm-demo
    app.kubernetes.io/managed-by: bnk-forge
  annotations:
    eks.amazonaws.com/role-arn: ${bedrock_role_arn}
automountServiceAccountToken: true
