apiVersion: k8s.f5net.com/v1alpha1
kind: F5BigAnalyzer
metadata:
  name: ${analyzer_name}
  namespace: ${namespace}
  labels:
    app.kubernetes.io/part-of: bedrock-smartllm-demo
    app.kubernetes.io/managed-by: bnk-forge
spec:
  name: ${analyzer_name}
  applications:
  - name: ${httproute_name}
    kind: HTTPRoute
    group: gateway.networking.k8s.io
    namespace: ${namespace}
  dataSources:
  - name: prometheus-bedrock
    endpoint: ${prometheus_endpoint}
    username: ""
    password: ""
  script:
    type: builtin
    builtin:
      name: LLMLoadMonitor
  schedule: ${analyzer_schedule}
