{{- if and (.Values.enabled) (not (lookup "v1" "Secret" .Release.Namespace "ipi-feedlist-credentials-secret")) }}
apiVersion: v1
kind: Secret
metadata:
  name: ipi-feedlist-credentials-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- end }}
