apiVersion: v1
kind: Service
metadata:
  name: smartllm-client
  namespace: ${namespace}
  labels:
    app.kubernetes.io/name: smartllm-client
    app.kubernetes.io/part-of: bedrock-smartllm-demo
    app.kubernetes.io/managed-by: bnk-forge
    release: ${prometheus_release_label}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: smartllm-client
  ports:
  - name: metrics
    port: 9100
    targetPort: metrics
