apiVersion: k8s.f5net.com/v1
kind: F5BigCneAddresslist
metadata:
  name: demo-blocked-sources
  namespace: ${gateway_namespace}
  labels:
    app.kubernetes.io/name: demo-blocked-sources
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: bnk-demo
    app.kubernetes.io/managed-by: bnk-forge
spec:
  addresses:
    - 198.51.100.0/24
