apiVersion: k8s.f5net.com/v1
kind: F5BigCnePortlist
metadata:
  name: demo-allowed-ports
  namespace: ${gateway_namespace}
  labels:
    app.kubernetes.io/name: demo-allowed-ports
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: bnk-demo
    app.kubernetes.io/managed-by: bnk-forge
spec:
  ports:
    - "80"
    - "443"
    - "8080"
