apiVersion: k8s.f5net.com/v1
kind: F5BigFwPolicy
metadata:
  name: demo-fw-policy
  namespace: ${gateway_namespace}
  labels:
    app.kubernetes.io/name: demo-fw-policy
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: bnk-demo
    app.kubernetes.io/managed-by: bnk-forge
spec:
  rule:
    - name: allow-web
      action: accept
      ipProtocol: tcp
      source:
        addressLists:
          - demo-allowed-sources
      destination:
        portLists:
          - demo-allowed-ports
      logging: true
    - name: block-bad-actors
      action: drop
      ipProtocol: any
      source:
        addressLists:
          - demo-blocked-sources
      logging: true
    - name: default-allow
      action: accept
      ipProtocol: any
      logging: false
