apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demo-smart-route
  namespace: ${gateway_namespace}
  labels:
    app.kubernetes.io/name: demo-smart-route
    app.kubernetes.io/component: routing
    app.kubernetes.io/part-of: bnk-demo
    app.kubernetes.io/managed-by: bnk-forge
spec:
  parentRefs:
    - name: ${gateway_name}
      sectionName: smart-http
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ${smart_backend_service_name}
          namespace: ${app_namespace}
          port: ${smart_backend_service_port}
          weight: 1
