apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: ${observability_namespace}
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: bnk-demo
    app.kubernetes.io/managed-by: bnk-forge
spec:
  selector:
    app.kubernetes.io/name: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      protocol: TCP
  type: ClusterIP
