apiVersion: v1
kind: Service
metadata:
  name: fluentbit-hsl-udp
  namespace: ${observability_namespace}
  labels:
    app.kubernetes.io/name: fluentbit-hsl
    app.kubernetes.io/part-of: bnk-demo
    app.kubernetes.io/managed-by: bnk-forge
spec:
  selector:
    app.kubernetes.io/name: fluentbit-hsl
  ports:
    - name: hsl-udp
      port: ${fluentbit_hsl_port}
      targetPort: ${fluentbit_hsl_port}
      protocol: UDP
  type: ClusterIP
